### ISSUE TITLE
UTF-8 detection detects ASCII in some cases

### ISSUE THREAD

**Issue by yourilima** [Ardem/yii-coding-standard#6]
the mb_detect_encoding function sometimes detects ASCII instead of utf8 and then gives an error.

reproduce:
create a file utf-8 encoded but with only ascii complient characters in it.
codesniff the file

it now says
"File must use only UTF-8 encoding. but ASCII found"

**Comment by Ardem** [comment]
Hi yourilima,

I know about this thing. But it appears if the encoding of your file is "us-ascii". Please show me the output result of this command:

file -bi yourfile.html

**Comment by yourilima** [comment]
```
text/x-c++; charset=us-ascii
```

Looks like you're right. Then I guess I'll have to go complain with the developer of my code-editor :P I explicitly "save with encoding"
