### ISSUE TITLE
utf-8 detection re-issued

### ISSUE THREAD

**Issue by yourilima** [Ardem/yii-coding-standard#7]
Hi,

sorry for opening this again.

The issue is still there as just like the mb_detect_encoding function file also just detects the encoding by which character type is found in it. therefor an utf-8 encoded file without characters outside the ascii range is detected as ascii. no matter how explicitly you say it should be saved as utf 8. opening the file in vim and asking ":set fileencoding?" or ":set encoding?" returns utf 8.

the detection fails because the function returns ascii (which is a subset of utf8) even though it is utf-8 encoded.

**Comment by Ardem** [comment]
Hi yourilima. I made a changes in encoding_list, please check it now.

**Comment by yourilima** [comment]
Works like a charm. Great work.
