### ISSUE TITLE
Make standard *really* installable via Composer

### ISSUE THREAD

**Issue by hijarian** [Ardem/yii-coding-standard#8]
There's a problem with sandboxed installation using Composer.

[PHP_CodeSniffer accepts the external standard only if it's toplevel directory is named the same as the standard](http://pear.php.net/manual/en/package.php.php-codesniffer.coding-standard-tutorial.php). So, after the following:

``` bash
$ php composer.phar install --dev
$ phpcs --standard=./vendor/ardem/yii-coding-standard ./src
```

I get the following irrelevant fatal error:

```
PHP Fatal error:  Cannot redeclare class Yii_Sniffs_Objects_ObjectParenthesesSniff in /home/hijarian/projects/YiiBooster/vendor/ardem/yii-coding-standard/Sniffs/Objects/ObjectParenthesesSniff.php on line 28
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->process() /usr/bin/phpcs:37
PHP   3. PHP_CodeSniffer->process() /usr/share/php/PHP/CodeSniffer/CLI.php:579
PHP   4. PHP_CodeSniffer->populateTokenListeners() /usr/share/php/PHP/CodeSniffer.php:462
PHP   5. PHP_CodeSniffer::autoload() /usr/share/php/PHP/CodeSniffer.php:0
PHP   6. include() /usr/share/php/PHP/CodeSniffer.php:283
```

After I rename `yii-coding-standard` to `Yii` (thus corrupting the Composer installation) the invocation

``` bash
$ phpcs --standard=./vendor/ardem/Yii ./src
```

does its job at last.

I suppose if you are going to have a Composer-installable library this issue should be resolved...

**Comment by Ardem** [comment]
Done. Please reinstall "yii-coding-standard", and use this command:

`$ phpcs --standard=./vendor/ardem/yii-coding-standard/Yii ./src`

**Comment by hijarian** [comment]
Awesome! Thank you, man.
